kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: source-pvc
  namespace: spring-petclinic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: local
  storageClassName: manual
  volumeMode: Filesystem
